//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHO_Json_TestConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHO_Json_TestConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;message&quot;: &quot;获取排行成功&quot;,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;id&quot;: 87013579,
        ///            &quot;artistId&quot;: 795196,
        ///            &quot;title&quot;: &quot;個展「明日、こもれび」&quot;,
        ///            &quot;type&quot;: &quot;illust&quot;,
        ///            &quot;caption&quot;: &quot;1月15日～1月24日にとらのあな様にて個展を開催することになりました。感染予防のため事前予約制となります。よろしくお願いいたします。詳細 &lt;a href=\&quot;https://news.toranoana.jp/153142\&quot; target=\&quot;_blank\&quot;&gt;https://news.toranoana.jp/153142&lt;/a&gt;&lt;br /&gt;【期　　間】：1月15日(金)～1月24日(日)　15:00～19:00　※初日のみ16:00オープン&lt;br /&gt;【場　　所】：とらのあな秋葉原店B　4階&quot;,
        ///            &quot;artistPreView&quot;: {
        ///                [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;message&quot;:&quot;获取画作详情成功&quot;,&quot;data&quot;:{&quot;id&quot;:86896933,&quot;artistId&quot;:4378,&quot;title&quot;:&quot;あーこちゃんまとめ&quot;,&quot;type&quot;:&quot;illust&quot;,&quot;caption&quot;:&quot;担当させていただいている、にじさんじ所属ライバー朝日南アカネさんのお祝い絵まとめです！&lt;br /&gt;&lt;br /&gt;■Youtubeチャンネル&lt;br /&gt;&lt;a href=\&quot;https://www.youtube.com/channel/UCe_p3YEuYJb8Np0Ip9dk-FQ\&quot; target=\&quot;_blank\&quot;&gt;https://www.youtube.com/channel/UCe_p3YEuYJb8Np0Ip9dk-FQ&lt;/a&gt;&quot;,&quot;artistPreView&quot;:{&quot;id&quot;:4378,&quot;name&quot;:&quot;えいひ&quot;,&quot;account&quot;:&quot;eihi&quot;,&quot;avatar&quot;:&quot;https://i.pximg.net/user-profile/img/2009/07/22/16/28/24/935667_48029b179068620d705e908f5eac3abd_170.jpg&quot;},&quot;tags&quot;:[ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Untitled_1 {
            get {
                return ResourceManager.GetString("Untitled_1", resourceCulture);
            }
        }
    }
}
