//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;message&quot;: &quot;获取画作详情成功&quot;,
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: 86896933,
        ///    &quot;artistId&quot;: 4378,
        ///    &quot;title&quot;: &quot;あーこちゃんまとめ&quot;,
        ///    &quot;type&quot;: &quot;illust&quot;,
        ///    &quot;caption&quot;: &quot;担当させていただいている、にじさんじ所属ライバー朝日南アカネさんのお祝い絵まとめです！&lt;br /&gt;&lt;br /&gt;■Youtubeチャンネル&lt;br /&gt;&lt;a href=\&quot;https://www.youtube.com/channel/UCe_p3YEuYJb8Np0Ip9dk-FQ\&quot; target=\&quot;_blank\&quot;&gt;https://www.youtube.com/channel/UCe_p3YEuYJb8Np0Ip9dk-FQ&lt;/a&gt;&quot;,
        ///    &quot;artistPreView&quot;: {
        ///      &quot;id&quot;: 4378,
        ///      &quot;name&quot;: &quot;えいひ&quot;,
        ///      &quot;account&quot;: &quot;eihi&quot;,
        ///      &quot;avatar&quot;: &quot;https://i.pximg.net/user-pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string j1 {
            get {
                return ResourceManager.GetString("j1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;message&quot;: &quot;获取排行成功&quot;,
        ///    &quot;data&quot;: [
        ///        {
        ///            &quot;id&quot;: 87013579,
        ///            &quot;artistId&quot;: 795196,
        ///            &quot;title&quot;: &quot;個展「明日、こもれび」&quot;,
        ///            &quot;type&quot;: &quot;illust&quot;,
        ///            &quot;caption&quot;: &quot;1月15日～1月24日にとらのあな様にて個展を開催することになりました。感染予防のため事前予約制となります。よろしくお願いいたします。詳細 &lt;a href=\&quot;https://news.toranoana.jp/153142\&quot; target=\&quot;_blank\&quot;&gt;https://news.toranoana.jp/153142&lt;/a&gt;&lt;br /&gt;【期　　間】：1月15日(金)～1月24日(日)　15:00～19:00　※初日のみ16:00オープン&lt;br /&gt;【場　　所】：とらのあな秋葉原店B　4階&quot;,
        ///            &quot;artistPreView&quot;: {
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string j2 {
            get {
                return ResourceManager.GetString("j2", resourceCulture);
            }
        }
    }
}
